# Generated by Django 3.1.3 on 2023-01-08 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_profile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Musinsa_m',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('codi_url', models.CharField(max_length=50)),
                ('shoes_url', models.CharField(max_length=50)),
                ('codi_rec', models.CharField(max_length=50)),
                ('shoes_rec', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Musinsa_w',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prd_title', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('brand', models.CharField(max_length=50)),
                ('price', models.FloatField(max_length=50)),
                ('codi_url', models.CharField(max_length=50)),
                ('shoes_url', models.CharField(max_length=50)),
                ('codi_rec', models.CharField(max_length=50)),
                ('shoes_rec', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
